export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000/api";
export const ENDPOINTS = {
  SIGN_UP: "/signup/",
  LOGIN: "/token/",
  LOGOUT: "/logout/",
  REFRESH_TOKEN: "/token/refresh/",
  USER_DATA: "/user/",
  USER_PROFILE: "/profile/",
  SEND_FOLLOW_REQUEST: "/friend-requests/send/",
  PENDING_FOLLOW_REQUESTS: "/friend-requests/pending/",
  PENDING_SENT_FOLLOW_REQUESTS: "/friend-requests/pending/sent/",
  ACCEPT_FOLLOW_REQUEST: "/friend-requests/accept/",
  REMOVE_FOLLOW_REQUEST: "/friend-requests/remove/",
  FOLLOWERS: "/followers/",
  FOLLOWING: "/following/",
  UNFOLLOW_USER: "/unfollow/",
  CREATE_POST: "/blog/create/",
  GET_ALL_POSTS: "/blog/all/",
  GET_POST_BY_ID: "/blog/",
  GET_MY_POSTS: "/blog/",  
  POST_COMMENT: "/blog/comment/",
  GET_COMMENTS: "/blog/comments/",
  GET_COMMENTS_COUNT: "/blog/comment-count/",
  POST_LIKE_COMMENT: "/comment/like/",
  GET_COMMENT_LIKES: "/comment/likes/",
  GET_COMMENT_LIKES_COUNT: "/comment/like-count/",
  POST_BLOG_LIKE: "/blog/like/",
  GET_BLOG_LIKES: "/blog/likes/",
  GET_BLOG_LIKES_COUNT: "/blog/like-count/",
};