export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000/api";
export const ENDPOINTS = {
  SIGN_UP: "/signup/",
  LOGIN: "/token/",
  LOGOUT: "/logout/",
  REFRESH_TOKEN: "/token/refresh/",
  USER_DATA: "/user/",
  USER_PROFILE: "/profile/",
  SEND_FOLLOW_REQUEST: "/friend-requests/send/",
  PENDING_FOLLOW_REQUESTS: "/friend-requests/pending/",
  PENDING_SENT_FOLLOW_REQUESTS: "/friend-requests/pending/sent/",
  ACCEPT_FOLLOW_REQUEST: "/friend-requests/accept/",
  REMOVE_FOLLOW_REQUEST: "/friend-requests/remove/",
  FOLLOWERS: "/followers/",
  FOLLOWING: "/following/",
  UNFOLLOW_USER: "/unfollow/",
  CREATE_POST: "/blog/create/",
  GET_ALL_POSTS: "/blog/all/",
  GET_MY_POSTS: "/blog/my/",
};